<a href="https://colab.research.google.com/github/Pravallikavyas/Task-7/blob/main/Copy_of_DataPreprocessing_Assignment11_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Data.csv

**Step 1: Importing the libraries**

In [3]:
import pandas as pd
import numpy as np


**Step 2: Importing dataset**

In [4]:
df=pd.read_csv("/content/Data.csv")
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
df.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [7]:
df.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

In [8]:
df=df.drop_duplicates()

In [9]:
df.shape

(10, 4)

**Step 3: Handling the missing data**

In [10]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [11]:
x=df['Age'].mean()

In [12]:
df['Age']=df['Age'].fillna(x)

In [13]:
df

Country        Age   Salary Purchased
0   France  44.000000  72000.0        No
1    Spain  27.000000  48000.0       Yes
2  Germany  30.000000  54000.0        No
3    Spain  38.000000  61000.0        No
4  Germany  40.000000      NaN       Yes
5   France  35.000000  58000.0       Yes
6    Spain  38.777778  52000.0        No
7   France  48.000000  79000.0       Yes
8  Germany  50.000000  83000.0        No
9   France  37.000000  67000.0       Yes

In [14]:
y=df['Salary'].mean()
y

63777.77777777778

In [15]:
df['Salary']=df['Salary'].fillna(y)

In [16]:
df

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

**Step 4: Encoding categorical data**

In [17]:
df["Purchased"]=df["Purchased"].map({'Yes':1,'No':0})

In [18]:
df

Country        Age        Salary  Purchased
0   France  44.000000  72000.000000          0
1    Spain  27.000000  48000.000000          1
2  Germany  30.000000  54000.000000          0
3    Spain  38.000000  61000.000000          0
4  Germany  40.000000  63777.777778          1
5   France  35.000000  58000.000000          1
6    Spain  38.777778  52000.000000          0
7   France  48.000000  79000.000000          1
8  Germany  50.000000  83000.000000          0
9   France  37.000000  67000.000000          1

**Step 5: Creating a dummy variable**

In [19]:
df.Country.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [21]:
df1=df['Country'].copy()
df1

0     France
1      Spain
2    Germany
3      Spain
4    Germany
5     France
6      Spain
7     France
8    Germany
9     France
Name: Country, dtype: object

In [23]:
df1=pd.get_dummies(df['Country'])

In [24]:
df1

France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
4       0        1      0
5       1        0      0
6       0        0      1
7       1        0      0
8       0        1      0
9       1        0      0

In [26]:
del df['Country']

In [27]:
df

Age        Salary  Purchased
0  44.000000  72000.000000          0
1  27.000000  48000.000000          1
2  30.000000  54000.000000          0
3  38.000000  61000.000000          0
4  40.000000  63777.777778          1
5  35.000000  58000.000000          1
6  38.777778  52000.000000          0
7  48.000000  79000.000000          1
8  50.000000  83000.000000          0
9  37.000000  67000.000000          1

In [30]:
df=pd.concat([df,df1],axis=1)

In [31]:
df

Age        Salary  Purchased  France  Germany  Spain
0  44.000000  72000.000000          0       1        0      0
1  27.000000  48000.000000          1       0        0      1
2  30.000000  54000.000000          0       0        1      0
3  38.000000  61000.000000          0       0        0      1
4  40.000000  63777.777778          1       0        1      0
5  35.000000  58000.000000          1       1        0      0
6  38.777778  52000.000000          0       0        0      1
7  48.000000  79000.000000          1       1        0      0
8  50.000000  83000.000000          0       0        1      0
9  37.000000  67000.000000          1       1        0      0

**Step 6: Splitting the datasets into training sets and Test sets**

In [36]:
X=df.loc[:,['Age','Salary','France','Germany','Spain']].values
y=df.loc[:,'Purchased'].values


In [49]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [50]:
X_train

array([[4.80000000e+01, 7.90000000e+04, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [2.70000000e+01, 4.80000000e+04, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00],
       [3.87777778e+01, 5.20000000e+04, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00],
       [3.50000000e+01, 5.80000000e+04, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [4.00000000e+01, 6.37777778e+04, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00],
       [3.70000000e+01, 6.70000000e+04, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [3.00000000e+01, 5.40000000e+04, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00],
       [3.80000000e+01, 6.10000000e+04, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00]])

In [46]:
X_test

array([[3.7e+01, 6.7e+04, 1.0e+00, 0.0e+00, 0.0e+00],
       [4.8e+01, 7.9e+04, 1.0e+00, 0.0e+00, 0.0e+00],
       [5.0e+01, 8.3e+04, 0.0e+00, 1.0e+00, 0.0e+00]])

In [47]:
y_train

array([0, 0, 1, 1, 0, 1, 0])

In [48]:
y_test

array([1, 1, 0])

**Step 7: Feature Scaling**

In [51]:
from sklearn.preprocessing import StandardScaler

In [54]:
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [55]:
X_train

array([[ 1.88440161,  2.03472003,  1.29099445, -0.57735027, -0.77459667],
       [-1.62448414, -1.34688467, -0.77459667, -0.57735027,  1.29099445],
       [ 0.34346236, -0.91054858, -0.77459667, -0.57735027,  1.29099445],
       [-0.28776576, -0.25604444,  1.29099445, -0.57735027, -0.77459667],
       [ 0.54768323,  0.3742188 , -0.77459667,  1.73205081, -0.77459667],
       [ 0.04641383,  0.72571176,  1.29099445, -0.57735027, -0.77459667],
       [-1.12321475, -0.69238053, -0.77459667,  1.73205081, -0.77459667],
       [ 0.21350363,  0.07120763, -0.77459667, -0.57735027,  1.29099445]])

In [56]:
X_test

array([[ 1.21604242,  1.27113188,  1.29099445, -0.57735027, -0.77459667],
       [ 2.2185812 ,  2.47105613, -0.77459667,  1.73205081, -0.77459667]])